[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install -g pnpm && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build && pnpm build:web"]

[start]
cmd = "node dist/server.js"
