[phases.setup]
nixPkgs = ["nodejs_22"]
cmds = [
  "npm install -g pnpm@9",
  "echo \"//npm.pkg.github.com/:_authToken=$NPM_GITHUB_TOKEN\" >> ~/.npmrc",
  "echo '@pushpress:registry=https://npm.pkg.github.com' >> ~/.npmrc",
]

[phases.install]
cmds = ["pnpm install --frozen-lockfile -r"]

[phases.build]
cmds = ["pnpm build && pnpm build:web"]

[start]
cmd = "node dist/server.js"
