[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildArgs = { NPM_GITHUB_TOKEN = "${{NPM_GITHUB_TOKEN}}" }

[deploy]
startCommand = "node dist/server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
